### ISSUE TITLE
NPM install fails since a recent PR

### ISSUE THREAD

**Issue by shmuli9** [jacobparis/underkill-stack#9]
I am getting this error on a clean `npm install` of the repo:

```
838 verbose stack Error: Unable to resolve reference $react
838 verbose stack     at get spec [as spec] (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/edge.js:202:15)
838 verbose stack     at #nodeFromEdge (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1036:46)
838 verbose stack     at #loadPeerSet (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1294:35)
838 verbose stack     at #nodeFromEdge (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1079:29)
838 verbose stack     at async #loadPeerSet (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1305:23)
838 verbose stack     at async #buildDepStep (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:901:11)
838 verbose stack     at async Arborist.buildIdealTree (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
838 verbose stack     at async Promise.all (index 1)
838 verbose stack     at async Arborist.reify (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
838 verbose stack     at async Install.exec (/usr/local/share/nvm/versions/node/v20.17.0/lib/node_modules/npm/lib/commands/install.js:150:5)
```

This seems to be related to this PR, #3

I might be doing something wrong, but if so, the README probably needs to be updated

You can verify by opening a codespace on main and seeing the IDE properly initialises when it attempts `npm install`

**Comment by jacobparis** [comment]
Fixed in #10
